version : '3.9'
services :   
  backend :
    image : backend
    name : backend
    environment : 
      spring.datasource.url: jdbc:mysql://mysql-container:3306/devops
      spring.datasource.username: root
      spring.datasource.password: raji123*
    ports :
    - "8080:8080"
    networks :
    - mine 
    volumes :
    - vol: /app
    restart : always
    depends_on : 
    - frontend
    - mysql-container
  mysql-container :
    image : mysql-container
    name : mysql-container
    ports :
    - "3306:3306"
    volumes :
    - vol: /app
    networks :
    - mine
  frontend :
    image : frontend
    name : frontend
    environment :
    - REACT_APP_SPRING_BOOT_URL=http://backend:8080
    ports :
    - "3000:3000"
    volumes :
    - vol: /app
    networks :
    - mine
    restart : always
networks : 
  mine :
volumes : 
  vol :

