version: '3.9'
services:
  backend:
    image: backend
    name: backend
    environment:
      - spring.datasource.url=jdbc:mysql://mysql-container:3306/devops
      - spring.datasource.username=root
      - spring.datasource.password=raji123*
    ports:
      - "8080:8080"
    networks:
      - mine
    volumes:
      - vol:/app
    restart: always
    depends_on:
      - mysql-container

  mysql-container:
    image: mysql-container # Use a valid MySQL image
    name: mysql-container
    ports:
      - "3306:3306"
    volumes:
      - vol:/app
    networks:
      - mine
    environment:
      - MYSQL_ROOT_PASSWORD=raji123* # Set the MySQL root password

  frontend:
    image: frontend
    name: frontend
    environment:
      - REACT_APP_SPRING_BOOT_URL=http://backend:8080
    ports:
      - "3000:3000"
    networks:
      - mine
    volumes:
      - vol:/app
    restart: always
    depends_on:
      - backend

networks:
  mine:

volumes:
  vol:
