version: '3.9'
services:
  backend: # raji2306/spring-boot:badass
    image: final-call
    container_name: backend
    environment:
      - spring.datasource.url=jdbc:mysql://mysql-container:3306/devops
      - spring.datasource.username=root
      - spring.datasource.password=raji123*
    ports:
      - "8080:8080"
    networks:
      - mine
    volumes:
      - vol:/app
    restart: always
    depends_on:
      - mysql-container
    deploy:
        resources:
            limits:
              cpus: 0.50
              memory: 512M
            reservations:
              cpus: 0.25
              memory: 128M
              
  mysql-container: # raji2306/database
    image: mysql-container # Use a valid MySQL image
    container_name: mysql-container
    ports:
      - "3306:3306"
    volumes:
      - vol:/app
    networks:
      - mine
    environment:
      - MYSQL_ROOT_PASSWORD=raji123* # Set the MySQL root password

networks:
  mine:

volumes:
  vol:
