name : Springboot-react-devops 

run-name : springboot-run

on :   #fork - Someone forks | gollum : Wiki updation | page_build : #Github Pages
  push :
    branches : 
    - master 
    - hot-fix
    - '!feature' # means branch ignore, you can use 'branch-ignore' or '!' 
    paths : 
    - '**.sh'
    tags : 
    - '**-milestone'
  branch_protection_rule :
    types: [created, deleted]
  issues:
    types: [opened, milestoned]
  pull_request:
    branches: [ master, hot-fix ]
  workflow_dispatch :
  # schedule:
  #   - cron: '61 25 * * *'

permissions: write-all # Set {} for no permissions
env:
  AUTHOR : production
  image : "mysql-boom"
  dockerfile : Dockerfile
defaults: #default settings, it can override if you speicific it on Job Level
  run:
    shell: bash

#---------------------------------------------- Building Doker Image for Mysql ------------------------------------------------------------------------------------------#

jobs :

  Building-docker-image :
    uses : ./.github/workflows/docker-workflow.yaml
    with :
      image : "mysql-boom"
      tags : ${{ github.run_number }}
      dockerfile : Dockerfile
    secrets:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD :  ${{ secrets.DOCKER_PASSWORD }}

#-----------------------------------------------------Testing our Application with Mysql Connectivity --------------------------------------------------------------------#

  Building-App : 
    needs : Building-docker-image
    runs-on : ubuntu-latest
    timeout-minutes: 10
    env:
      COUNT: 31
    services:
      mysql:
        image: raji2306/mysql-boom:${{ github.run_number }} # raji2306/mysql-boom:${{ github.run_number }}
        credentials:
          username: ${{ secrets.DOCKERHUB_USERNAME }} 
          password: ${{ secrets.DOCKERHUB_TOKEN }}
        env:
          MYSQL_ROOT_PASSWORD: raji123*
          MYSQL_DATABASE: devops
        ports:
          - 3306/tcp
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps :
    - name : Giving permission to our Repository
      uses: actions/checkout@v2
      
    - name: Set up JDK 17 for x64
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
      
    - name : Building Maven project
      run: mvn -B package --file ./spring-backend/pom.xml

    - name: 'Upload Artifact'
      uses: actions/upload-artifact@v3
      with:
        name: my-artifact
        path: ./springboot-react-Devops/springboot-react-Devops/spring-backend/devops-proj.jar
        retention-days: 5

#-------------------------------------------------------------------Building Spring-boot Docker Image ------------------------------------------------------------------------------#

  # Building-spring-boot-image :
  #   uses : ./.github/workflows/docker-workflow.yaml
  #   with :
  #     image : "spring-image"                   # For 'mysql-boom' database 
  #     tags : ${{ github.run_number }}
  #     dockerfile : ./spring-backend/Dockerfile # Use Dockerfile Location
  #   secrets:
  #     DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  #     DOCKER_PASSWORD :  ${{ secrets.DOCKER_PASSWORD }}

#----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------#

